package com.chimera.learnservice.model;

import com.chimera.contentcreator.model.ContentType;
import com.chimera.trendwatcher.model.Platform;

import java.time.Instant;
import java.util.List;
import java.util.Map;

/**
 * Point-in-time performance report generated by the LEARN service.
 *
 * Distributed to:
 * - CREATE service  via {@link com.chimera.learnservice.feedback.CreateFeedbackAdapter}
 * - PERCEIVE service via {@link com.chimera.learnservice.feedback.PerceiveFeedbackAdapter}
 *
 * @param id                     Unique report identifier
 * @param topPerformersByPlatform Best-performing content per platform (Rule: track best per platform)
 * @param topPerformingTopics     Topics with EXCELLENT or GOOD rating — prioritise in CREATE and PERCEIVE
 * @param underperformingTopics   Topics with POOR or NEGATIVE rating — flag and report back (Rule: negative flagged)
 * @param negativeContentIds      ContentPiece IDs with NEGATIVE rating — discard patterns from these
 * @param overallEngagementScore  Rolling average score across all recent content [0.0 – 1.0]
 * @param engagementByContentType Average score per ContentType — informs CREATE's GenerationParameters
 * @param totalContentAnalyzed    Total content pieces in the analysis window
 * @param negativePerformanceCount Number of NEGATIVE-rated pieces in this window
 * @param generatedAt             UTC timestamp of report generation
 */
public record FeedbackReport(
        String id,
        Map<Platform, List<ContentPerformance>> topPerformersByPlatform,
        List<String> topPerformingTopics,
        List<String> underperformingTopics,
        List<String> negativeContentIds,
        double overallEngagementScore,
        Map<ContentType, Double> engagementByContentType,
        int totalContentAnalyzed,
        int negativePerformanceCount,
        Instant generatedAt
) {}
